default_install_hook_types:
  [pre-commit, pre-push, commit-msg, prepare-commit-msg]
repos:
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.12.0
    hooks:
      - id: pretty-format-java
        args: [--autofix, --google-java-formatter-version=1.21.0]

  - repo: local
    hooks:
      - id: check_committer_email
        name: Check Committer email Id
        entry: python check_email_domain.py
        language: python
        stages: [pre-commit]
